#! /bin/bash

cd ${HOME}/wyoming-satellite/ || exit 1

python3 -m venv .venv
.venv/bin/pip3 install --upgrade pip
.venv/bin/pip3 install --upgrade wheel setuptools
.venv/bin/pip3 install \
  -f 'https://synesthesiam.github.io/prebuilt-apps/' \
  -r requirements.txt \
  -r requirements_audio_enhancement.txt \
  -r requirements_vad.txt

status_code=$(script/run --help)

#TODO: verify ge check
if [[ $status_code -ge 1 ]]; then
  exit 1
fi
