#! /bin/bash
cd $HOME
sudo apt-get update && sudo apt-get install --no-install-recommends -y \
  git \
  python3-venv \
  libopenblas-dev

# Repos needed
git clone https://github.com/rhasspy/wyoming-satellite.git && git clone https://github.com/rhasspy/wyoming-openwakeword.git

cd wyoming-satellite/ && sudo bash etc/install-respeaker-drivers.sh
sudo reboot